command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  # Set your SQL Warehouse ID for AI document parsing
  # Find this in Databricks SQL > SQL Warehouses > [Your Warehouse] > Configuration
  - name: DATABRICKS_WAREHOUSE_ID
    value: "75fd8278393d07eb"
